name: Build BoutikCredit APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
      - name: google-services
        run: echo '{"project_info":{"project_number":"695609211507","project_id":"egcsarlu-app-b2ba4","storage_bucket":"egcsarlu-app-b2ba4.firebasestorage.app"},"client":[{"client_info":{"mobilesdk_app_id":"1:695609211507:android:461499ea4c20493e2c8806","android_client_info":{"package_name":"com.boutikcredit.app"}},"api_key":[{"current_key":"AIzaSyAjKGNOv-cbv7PPN8vYPDf2eAOSuGLNVQQ"}],"services":{"appinvite_service":{"other_platform_oauth_client":[]}}}],"configuration_version":"1"}' > android/app/google-services.json
      - run: flutter pub get
      - run: flutter build apk --release --no-tree-shake-icons --split-per-abi || true
      - uses: actions/upload-artifact@v4
        with:
          name: BoutikCredit-APK
          path: android/app/build/outputs/flutter-apk/*.apk
